# Run test when triggering the workflow on push and pull request,
# but only for the headless branch

name: test

on:
  push:
    branches:
      - headless

  pull_request:
    branches:
      - headless

# -----------------------------------------------------------------------------------------------------
# To leverage the benefit of Github Action, the testing process is divided into three jobs:
#   1. pdf2docx: convert sample pdf to docx -> linux runner
#   2. docx2pdf: convert generated docx to pdf for comparing -> specific runner with MS Word installed
#   3. check_quality: convert page to image and compare similarity with python-opencv -> linux runner
# -----------------------------------------------------------------------------------------------------
jobs:
  pdf2docx:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        python-version: ["3.8", "3.9", "3.10"]

    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pytest pytest-cov codecov
          python setup.py develop

      - name: Run unit test
        run: |
          pytest -v ./test/test.py::TestConversion --cov=./pdf2docx --cov-report=xml

      # upload docx for further job
      - name: Archive package
        uses: actions/upload-artifact@v2
        with:
          name: outputs
          path: ./test/outputs
